BaSP-TG-6: Projects Page - Add/Edit Form
BaSP-a2022/marta-b-trackgenix-app pull request #10
Opened 2022-11-02 03:33 UTC by DamianPalavecino

- Create add/edit form including: Project Name, Description, Start Date, End Date, Client Name
- Redirect to Projects List (Name - Description - Client - Start Date- End Date - Employees - Actions)
- On add functionality the default value for Status is "inactive"
- On edit functionality should show previuos info
- Success message for confirmation edit and add actions
- Redirect to add/edit form page

2022-11-03 04:57 UTC, mara666 commented on src/Components/Projects/modal.module.css
> +    color: white;
colors must be in hexa!

2022-11-03 05:00 UTC, mara666 commented on src/Components/Projects/projectForm.jsx
> +      console.log(inputValue);
please, delete this console.log()

2022-11-03 05:02 UTC, mara666 commented on src/Components/Projects/projectForm.jsx
> +          alert('Project was created successfully');
here you can also print message from BE, like line 76

2022-11-03 05:03 UTC, mara666 commented on src/Components/Projects/projectForm.jsx
> +          alert('Project was successfully edited');
here you can also print message from BE, like line 59

2022-11-03 11:54 UTC, martumoser commented on src/Components/Projects/projectForm.jsx
> +          alert('Project was created successfully');
I'm not sure that the response of the endpoint includes a message. Check that before do the changes

2022-11-04 02:48 UTC, DamianPalavecino commented on src/Components/Projects/modal.module.css
> +    color: white;
Done

2022-11-04 02:48 UTC, DamianPalavecino commented on src/Components/Projects/projectForm.jsx
> +      console.log(inputValue);
Done

2022-11-04 13:16 UTC, Juanoauil requested changes

2022-11-04 13:16 UTC, Juanoauil commented on src/Components/Projects/projectForm.jsx
> +      if (id) {
why do you ask twice for the id

2022-11-04 13:16 UTC, Juanoauil commented on src/Components/Projects/projectForm.jsx
> +      console.log(JSON.stringify(inputValue));
please remove console.log

2022-11-04 20:30 UTC, DamianPalavecino commented on src/Components/Projects/projectForm.jsx
> +          alert('Project was created successfully');
Done

2022-11-04 20:33 UTC, DamianPalavecino commented on src/Components/Projects/projectForm.jsx
> +      console.log(JSON.stringify(inputValue));
Done

2022-11-04 20:33 UTC, DamianPalavecino commented on src/Components/Projects/projectForm.jsx
> +      if (id) {
Mistake, fixed

2022-11-04 20:33 UTC, DamianPalavecino commented on src/Components/Projects/projectForm.jsx
> +          alert('Project was successfully edited');
Done

2022-11-05 21:40 UTC, DamianPalavecino commented on src/Components/Projects/index.jsx
> +            projects.map((project) => {
Done

2022-11-05 21:47 UTC, Juanoauil approved these changes

2022-11-05 21:48 UTC, mara666 approved these changes
Good job Dami!

2022-11-06 00:55 UTC, cami-diaz commented
I can edit a project and save it without filling in the customer name. But in the projects list it keeps coming out with the old data.
![image](https://user-images.githubusercontent.com/109966958/200149001-1c61d3e8-b350-4fd4-a52d-a116c2a1c374.png)

2022-11-06 01:32 UTC, cami-diaz commented
Employees added to the project cannot be viewed. There is also no option in the form to add employee when adding or editing a project.

![image](https://user-images.githubusercontent.com/109966958/200149868-a5207517-8195-40c3-b98d-f3be52281ed8.png)

2022-11-06 22:02 UTC, merged