BaSP-TG-35: admins add shared components
BaSP-a2022/marta-b-trackgenix-app pull request #18
Opened 2022-11-09 02:33 UTC by Maxi-SR

- Add button component in add, edit and delete.
- Add modal component when you click on button component.
- Add table component.
- Add row component in table component.
- Add React Router to manage routes.

2022-11-09 16:05 UTC, martumoser requested changes
Why you are adding again the row and table shared component?

2022-11-09 16:05 UTC, martumoser commented on src/Components/Admins/index.js
> +      <Modal
why you are doing this?

2022-11-09 16:05 UTC, martumoser commented on src/Components/Admins/index.js
>    };
I don't understand this logic. toggleModal only has to open and close the modal

2022-11-09 16:05 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/superAdmins/${id}`, {
you don't have to make this changes. Superadmin is the one who see the admin list

2022-11-09 16:05 UTC, martumoser commented on src/Components/Admins/index.js
>      await fetch(`${process.env.REACT_APP_API_URL}/admins`)
Admin should see the list of employees and the projects

2022-11-09 23:41 UTC, Maxi-SR commented on src/Components/Admins/index.js
> +      <Modal
I do not understand the question, why I'm doing what? The return?

2022-11-09 23:42 UTC, Maxi-SR commented on src/Components/Admins/index.js
>    };
It's depends on how many modals you have to open, sometimes you have to open a modal when other closes. It's explained in the modal PR.

2022-11-09 23:43 UTC, Maxi-SR commented on src/Components/SuperAdmins/index.js
> +    await fetch(`${process.env.REACT_APP_API_URL}/superAdmins/${id}`, {
My fault, I was wrong when I changed entities.

2022-11-09 23:43 UTC, Maxi-SR commented on src/Components/Admins/index.js
>      await fetch(`${process.env.REACT_APP_API_URL}/admins`)
solved

2022-11-10 07:55 UTC, DamianPalavecino commented on src/Components/Admins/form.jsx
> +    history.push('/admins');
```suggestion
    history.goBack();
```

2022-11-11 13:27 UTC, martumoser requested changes

2022-11-11 20:21 UTC, Maxi-SR commented on src/Components/Admins/index.js
> +          <Button
done

2022-11-11 20:21 UTC, Maxi-SR commented on src/Components/Admins/index.js
> +        }
I tried this but I can't, I will try again

2022-11-12 00:25 UTC, Maxi-SR commented on src/Components/Admins/index.js
> +        }
done

2022-11-12 00:57 UTC, PilarFernandezC approved these changes
Looks good to me

2022-11-12 02:47 UTC, Juanoauil approved these changes

2022-11-12 10:14 UTC, martumoser approved these changes

2022-11-12 12:44 UTC, EliasBermudez13 commented
Looks good, nice Job!!

2022-11-12 13:33 UTC, merged