BaSP-TG-2: Super Admin - List and Delete
BaSP-a2022/marta-b-trackgenix-app pull request #2
Opened 2022-11-01 12:30 UTC by PilarFernandezC

- Shows list of admins
- Delete functionality with warning and success message
- Edit and Add buttons that redirects you to add form

2022-11-01 15:58 UTC, martumoser requested changes

2022-11-01 15:58 UTC, martumoser commented on src/Components/SuperAdmins/Modal/modal.module.css
> +    color: white;
Please keep consistency between the use of colors on hex or with the color name. We suggest to use color hex

2022-11-01 15:58 UTC, martumoser commented on src/Components/Layout/index.js
> +      break;
Please move this case to lines 21, above the /super-admins case

2022-11-01 15:58 UTC, martumoser commented on src/Components/SuperAdmins/List/List.jsx
> +const List = ({ admin, handleDelete }) => {
in this case admin is plural (admins) because it is the array with all admins

2022-11-01 20:31 UTC, PilarFernandezC commented on src/Components/SuperAdmins/Modal/modal.module.css
> +    color: white;
done

2022-11-01 20:32 UTC, PilarFernandezC commented on src/Components/Layout/index.js
> +      break;
done

2022-11-01 20:32 UTC, PilarFernandezC commented on src/Components/SuperAdmins/List/List.jsx
> +const List = ({ admin, handleDelete }) => {
done

2022-11-01 20:55 UTC, martumoser approved these changes

2022-11-03 02:20 UTC, DamianPalavecino approved these changes

2022-11-04 15:20 UTC, merged