BaSP-36: Super admins add shared components
BaSP-a2022/marta-b-trackgenix-app pull request #20
Opened 2022-11-09 02:40 UTC by mara666

In component SuperAdmins (index):
- Use Button component
- Use Modal component
- Use Table component
- Use Row component
- Implement useParams() and useHistory() where was needed
- Set routes in Layout component to edit and delete super-admins

Modals for messages in edit and create are display in alerts (we will change it later)

2022-11-09 15:12 UTC, martumoser requested changes
Please delete files that you are not using since you implement the shared components

2022-11-09 15:12 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +  const toggleModal = (modal, secondModal) => {
I don't understand this logic. toggleModal only has to open and close the modal.

2022-11-09 15:12 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +  const [showModal, setShowModal] = useState({ confirm: false, success: false });
why you are declaring this state as an object?

2022-11-09 15:12 UTC, martumoser commented on src/Components/SuperAdmins/index.js
> +      >
Why you are using this modal?

2022-11-09 17:29 UTC, mara666 commented on src/Components/SuperAdmins/index.js
> +      >
This modal is the message to confirm the delete. I forgot to change "project" instead of "Admin". It's a typo error.

2022-11-09 17:35 UTC, mara666 commented on src/Components/Layout/index.js
>                <Route exact path={'/super-admins/form'} component={SuperAdminForm} />
Yes, we use this path to edit one specific Admin.

2022-11-09 17:40 UTC, mara666 commented on src/Components/SuperAdmins/index.js
> +  const [showModal, setShowModal] = useState({ confirm: false, success: false });
this is because we use the logic defined in the Modal shared component. You can see the how to use it in this PR made by Dami --> https://github.com/BaSP-a2022/marta-b-trackgenix-app/pull/13

2022-11-09 17:40 UTC, mara666 commented on src/Components/SuperAdmins/index.js
> +  const toggleModal = (modal, secondModal) => {
this is because we use the logic defined in the Modal shared component. You can see the how to use it in this PR made by Dami --> https://github.com/BaSP-a2022/marta-b-trackgenix-app/pull/13

2022-11-10 04:05 UTC, Juanoauil approved these changes

2022-11-10 07:37 UTC, DamianPalavecino commented on src/Components/SuperAdmins/Form/Form.jsx
>        input.status = input.status === 'active' ? true : false;
```suggestion
      input.status = input.status === 'active'
```

2022-11-10 07:41 UTC, DamianPalavecino commented on src/Components/SuperAdmins/Form/Form.jsx
>            ) : (
```suggestion
          ) :  null}
```

You don't need to show status on create

2022-11-10 07:47 UTC, DamianPalavecino commented on src/Components/SuperAdmins/index.js
> +    history.push('/super-admins');
```suggestion
    history.goBack();
```

2022-11-10 20:42 UTC, mara666 commented on src/Components/SuperAdmins/Form/Form.jsx
>        input.status = input.status === 'active' ? true : false;
ty

2022-11-10 20:42 UTC, mara666 commented on src/Components/SuperAdmins/Form/Form.jsx
>            ) : (
ty Dami! I fix it

2022-11-10 21:02 UTC, DamianPalavecino approved these changes
Everything looks fine, good job Dario

2022-11-10 23:02 UTC, martumoser approved these changes

2022-11-11 00:08 UTC, EliasBermudez13 commented
Nice job!! Looks really fine!!
Only one comment: When editing SuperAdmin the validations for empty fields in form happen only if first the field is not valid.
Let my try to explain. If the field is empty by selecting what is in the field and then erasing there are no validations in form for that empty field, modal with Admin edited successfully message displays despite that there are empty fields.
Luckily empty data is not updated in the list. 
It's a rare bug but I have to report it.

2022-11-11 01:58 UTC, merged