BaSP-TG-34: Employee, added shared components
BaSP-a2022/marta-b-trackgenix-app pull request #22
Opened 2022-11-09 03:59 UTC by FabianDutraSilva

- Add shared components (Button, Modal, Table, Row)
- Modify form so edit functionality work correctly
- Add routes to Layout (Edit and Delete functionalities)

![image](https://user-images.githubusercontent.com/109638975/200735083-a9481ec1-3fc1-4d56-b9e1-a554193a8f81.png)

2022-11-10 04:35 UTC, Juanoauil requested changes

2022-11-10 04:35 UTC, Juanoauil commented on src/Components/Shared/Row/index.jsx
> +export default Row;
this component was not already merge?

2022-11-10 04:35 UTC, Juanoauil commented on src/Components/Employees/Form/index.js
>          alert('Employee added', data.message);
are these alerts correct? you shouldnt implement shared modal?

2022-11-10 04:35 UTC, Juanoauil commented on src/Components/Employees/Form/index.js
>  import style from '../employees.module.css';
please add styles to form

2022-11-10 04:35 UTC, Juanoauil commented on src/Components/Shared/Table/index.jsx
> +export default Table;
this component was not already merge?

2022-11-10 04:35 UTC, Juanoauil commented
please resolve conflict when you create a pr

2022-11-10 22:08 UTC, FabianDutraSilva commented on src/Components/Employees/Form/index.js
>          alert('Employee added', data.message);
fixed

2022-11-10 22:09 UTC, FabianDutraSilva commented on src/Components/Shared/Row/index.jsx
> +export default Row;
fixed

2022-11-10 22:09 UTC, FabianDutraSilva commented on src/Components/Shared/Table/index.jsx
> +export default Table;
solved conflicts on this branch

2022-11-10 22:37 UTC, FabianDutraSilva commented on src/Components/Employees/Form/index.js
>  import style from '../employees.module.css';
fixed

2022-11-11 03:12 UTC, PilarFernandezC approved these changes

2022-11-11 17:59 UTC, Juanoauil approved these changes

2022-11-11 18:27 UTC, SteampunkMatu commented
Looks great but I need you to move the button add only below of the "Employee" title thus we maintain consistency with the rest of the entities. Do that when you have time

2022-11-11 18:49 UTC, mara666 commented
Okey! I fix it. Ty @SteampunkMatu

2022-11-11 19:02 UTC, DamianPalavecino approved these changes
Changes were made correctly, approved

2022-11-11 19:10 UTC, merged