BaSP-TG-05: list and delete employees
BaSP-a2022/marta-b-trackgenix-app pull request #3
Opened 2022-11-01 21:02 UTC by Maxi-SR

- List employees
- Delete a subset of employees
Note: When you try to assign employees to a project in the backend, it is not working, so if you wants to see the projects of an employee you have to push projects when you are creating an employee. 
Another thing, I put modals for now when you click edit or add an employee, in the next PR I'm going to redirect to another page.

2022-11-02 02:10 UTC, Juanoauil requested changes

2022-11-02 02:10 UTC, Juanoauil commented on package.json
> +    "format": "prettier --write './**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc.json",
please revert this change

2022-11-02 02:10 UTC, Juanoauil commented on .eslintrc.json
> -    "settings": {
please revert this change

2022-11-02 02:10 UTC, Juanoauil commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/type-fest/-/type-fest-0.13.1.tgz",
revert changes in package.json and package-lock.json

2022-11-02 02:10 UTC, Juanoauil commented on src/Components/Employees/Modal/index.js
> +function Modal(props) {
you can use arrow functions

2022-11-02 02:10 UTC, Juanoauil commented on src/Components/Employees/index.js
> +    if (evt.target.checked == true) {
if you compare, should be with ===

2022-11-02 02:10 UTC, Juanoauil commented on src/Components/Employees/index.js
> +    setEmployees((current) => current.filter((x) => !checkedEmployees.includes(x._id)));
please replace checkedEmployee instead x

2022-11-03 02:18 UTC, Maxi-SR commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/type-fest/-/type-fest-0.13.1.tgz",
Damian sent to me his file

2022-11-03 02:19 UTC, Maxi-SR commented on .eslintrc.json
> -    "settings": {
Damian sent to me his file

2022-11-03 02:20 UTC, Maxi-SR commented on package.json
> +    "format": "prettier --write './**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc.json",
done

2022-11-03 02:22 UTC, Maxi-SR commented on src/Components/Employees/index.js
> +    setEmployees((current) => current.filter((x) => !checkedEmployees.includes(x._id)));
Done

2022-11-03 02:23 UTC, Maxi-SR commented on src/Components/Employees/index.js
> +    if (evt.target.checked == true) {
Done

2022-11-03 04:35 UTC, PilarFernandezC commented on src/Components/Employees/Modal/modal.module.css
> +  background-color: rgba(0, 0, 0, 0.5);
Keep consistency between the use of colors. We were suggested to use color hex

2022-11-03 04:35 UTC, PilarFernandezC commented on src/Components/Employees/Modal/modal.module.css
> +  border: solid black 1px;
Same here

2022-11-03 04:39 UTC, PilarFernandezC commented on src/Components/Employees/list.module.css
> +  background-color: rgba(55, 56, 103, 0.1);
Same here

2022-11-03 04:43 UTC, PilarFernandezC requested changes
Please, check all the colors

2022-11-04 00:13 UTC, Maxi-SR commented on src/Components/Employees/Modal/modal.module.css
> +  background-color: rgba(0, 0, 0, 0.5);
done

2022-11-04 00:14 UTC, Maxi-SR commented on src/Components/Employees/Modal/modal.module.css
> +  border: solid black 1px;
done

2022-11-04 00:14 UTC, Maxi-SR commented on src/Components/Employees/list.module.css
> +  background-color: rgba(55, 56, 103, 0.1);
done

2022-11-05 02:51 UTC, DamianPalavecino commented on src/Components/Employees/Modal/index.js
> +const Modal = (props) => {
```suggestion
const Modal = ({ show, title, confirmChanges, closeModal }) => {
```

2022-11-05 02:58 UTC, DamianPalavecino commented on src/Components/Employees/index.js
> +    if (evt.target.checked === true) {
```suggestion
    if (evt.target.checked) {
```

2022-11-05 03:00 UTC, DamianPalavecino commented on src/Components/Employees/index.js
> +
Remove linebreaks inside of function

2022-11-05 15:16 UTC, Maxi-SR commented on src/Components/Employees/index.js
> +
done

2022-11-05 18:08 UTC, Juanoauil commented on src/Components/Employees/Modal/modal.module.css
> +  background-color: #000000;
please change to  `background-color: rgba(0, 0, 0, .5);`

2022-11-05 19:19 UTC, Maxi-SR commented on src/Components/Employees/Modal/modal.module.css
> +  background-color: #000000;
done

2022-11-05 19:55 UTC, DamianPalavecino approved these changes
Approved, well done

2022-11-05 20:02 UTC, Juanoauil approved these changes

2022-11-05 22:03 UTC, PilarFernandezC approved these changes

2022-11-05 22:55 UTC, cami-diaz commented
When I delete one employee works fine. But when you try to delete another one, the app crashed. I attached the screenshot

![image](https://user-images.githubusercontent.com/109966958/200144386-49f03a5a-fc4c-46d2-a5eb-f4aa6e141b43.png)

2022-11-05 22:57 UTC, cami-diaz commented
The ticket says that there should be action icons (delete-edit) for each row. In this screen we only have the edit icon for each row, the delete is handle with checkboxes, should change this.

![image](https://user-images.githubusercontent.com/109966958/200144409-5298c2aa-999d-401b-8572-b4d55212fd8e.png)

2022-11-05 22:59 UTC, cami-diaz commented
The add and edit buttons should redirect to add or edit form, but for now it only show up a modal without functionality or redirect. Please fix that according to the ticket.

2022-11-05 23:00 UTC, cami-diaz commented
The data on each row should be align with the header of each column. I attached how is display so far.

![image](https://user-images.githubusercontent.com/109966958/200144563-30096987-7098-472f-8b74-0383e7e985c2.png)

2022-11-05 23:21 UTC, Juanoauil requested changes
app crashes when we remove two employees together

2022-11-06 00:02 UTC, cami-diaz commented
project information not visible

![image](https://user-images.githubusercontent.com/109966958/200147772-0bd8bea1-12d0-4f66-9301-4bfa66ca1c05.png)

2022-11-06 22:47 UTC, Juanoauil approved these changes

2022-11-06 22:49 UTC, merged