BaSP-TG-56: Super admins redux create, update and delete
BaSP-a2022/marta-b-trackgenix-app pull request #30
Opened 2022-11-15 19:52 UTC by mara666

### What has developed?

**- Create _constants_ to:**
  - create an admin
  - update an admin
  - delete an admin
  - get by id an admin

**- Create _actions_ to:**
  - create an admin
  - update an admin
  - delete an admin
  - get by id an admin

**- Create _thunks_ to:**
  - create an admin
  - update an admin
  - delete an admin
  - get by id an admin

**- Complete superAdmins _reducer_ to:**
  - create an admin
  - update an admin
  - delete an admin
  - get by id an admin

**- Connect _superAdmins component_ with store to:**
  - create an admin
  - update an admin
  - delete an admin
  - get by id an admin

### How to test?:
To test this ticket we should open the link of the app deployed in Vercel. Then, we should verify the correct functionality of:

- In the super admins table, the data has to be retrieved correctly and fill the table with all data Admins.
- In the super admins table, when clicking the delete button of a row, there should be a confirmation modal to delete a super admin. In case of 'No', modal should be closed and in case of 'Yes', it should delete the selected admin.
- When clicking on the edit button inside super admins table row, it should navigate to the super admins form page. We should check that the form gets all the admin info and we should update all the changes we made. Once confirmed all these changes, it should navigate back to the super admins table and it should reflect all changes made in the admin who was selected.
- When clicking on the add button in the super admins table page, it should navigate to the super admins form page. We should complete the form with data and press the confirm button. It should navigate to the super admins table and a new row of admin should appear, with all new data.

The main objective of this test is to verify the correct functionality of the app **_after redux implementation_**.

2022-11-16 03:10 UTC, Juanoauil requested changes

2022-11-16 03:10 UTC, Juanoauil commented on src/Components/SuperAdmins/Form/Form.jsx
> +      toggleModal(status);
you shouldn't use toggleModal before initialization

2022-11-16 03:10 UTC, Juanoauil commented on src/redux/super-admins/reducer.js
> +        request: 'GET'
you shouldn't set request in redux

2022-11-16 03:10 UTC, Juanoauil commented on src/Components/SuperAdmins/Form/Form.jsx
> +    if (request === 'GETBYID') {
remove unnecessary condition

2022-11-16 03:43 UTC, Juanoauil commented on src/Components/SuperAdmins/Form/Form.jsx
> +      toggleModal(status);
please move toggleModal into onSubmit

2022-11-16 20:29 UTC, mara666 commented on src/Components/SuperAdmins/Form/Form.jsx
> +      toggleModal(status);
Fixed!

2022-11-16 20:29 UTC, mara666 commented on src/redux/super-admins/reducer.js
> +        request: 'GET'
sorry, I removed status and request

2022-11-16 20:30 UTC, mara666 commented on src/Components/SuperAdmins/Form/Form.jsx
> +    if (request === 'GETBYID') {
removed!

2022-11-17 16:39 UTC, cami-diaz commented
Hello Dami! When editing a superAdmin and confirming the new data entered, I get this attached modal. I suggest that the message is "SuperAdmin was edited successfully "

![image](https://user-images.githubusercontent.com/109966958/202503112-88706baa-e31b-44d1-8502-0c7d2db7c00a.png)

2022-11-17 18:14 UTC, Juanoauil approved these changes

2022-11-17 18:39 UTC, DamianPalavecino reviewed
Replace `status: ''` with `status: false` in line 13 of Form.jsx to fix the issue "Error: status must be a boolean"

2022-11-17 19:20 UTC, PilarFernandezC approved these changes

2022-11-17 20:09 UTC, mara666 commented
Fixed all issues!

2022-11-17 20:56 UTC, merged