BaSP-TG-61 : employees create, update & delete with redux
BaSP-a2022/marta-b-trackgenix-app pull request #31
Opened 2022-11-15 22:21 UTC by Maxi-SR

-  Create employee : 
When clicking on the add button in the admin's table page, it should navigate to the admin's form page. We should complete the form with data and press the confirm button. It should navigate to the admin's table and a new row of admin's should appear, with all new data.
-  Delete employee : 
In the admin's table, when clicking the delete button of a row, a confirmation modal is open to delete an admin. In case of 'No', the modal should be closed and in case of 'Yes', it should delete the selected admin. 
-  Edit an employee : 
When clicking on the edit button inside admin's table row, it should navigate to the admin's form page. We should check that the form gets all the admin info and we should update all the changes we made. Once confirmed all these changes, it should navigate back to the admin's table and it should reflect all changes made.

2022-11-16 04:04 UTC, Juanoauil requested changes

2022-11-16 04:04 UTC, Juanoauil commented on src/redux/employees/reducer.js
> +        status: 'pending',
Is it necessary to have a status when there is an isPending?

2022-11-17 19:43 UTC, Maxi-SR commented on src/Components/Employees/index.js
>    );
done

2022-11-17 19:56 UTC, Maxi-SR commented on src/Components/Employees/Form/index.js
> +      toggleModal(status);
done

2022-11-17 19:57 UTC, Maxi-SR commented on src/redux/employees/reducer.js
> +        request: 'GET'
done

2022-11-17 19:57 UTC, Maxi-SR commented on src/redux/employees/reducer.js
> +        status: 'pending',
done

2022-11-17 21:07 UTC, mara666 approved these changes
Good job Maxi!

2022-11-18 00:43 UTC, Juanoauil approved these changes

2022-11-18 02:04 UTC, EliasBermudez13 commented
Looks good to me, nice job its aprooved.

2022-11-18 02:09 UTC, merged