BaSP-TG-4: Projects Page - List and Delete
BaSP-a2022/marta-b-trackgenix-app pull request #4
Opened 2022-11-01 21:44 UTC by DamianPalavecino

- Show table with projects list - Columns: Project name, Start date, Description, Client, Employees, Status, Actions.
- Add delete row functionality
- Add actions icon (delete and edit) for each row
- Create modal for warning message when deleting a project
- Create modal for Success message when project is deleted
- Add "Add new Project" button and redirect to add form
- Add a button 'See Employees'. This redirects to a list of employees per project

2022-11-02 02:26 UTC, Juanoauil requested changes

2022-11-02 02:26 UTC, Juanoauil commented on src/Components/Projects/index.jsx
> +          {projects === undefined && <p>There are no projects</p>}
you can use {`projects.length > 0 ? projects.map(() => ... : <p> There are no projects </p>`}

2022-11-03 13:29 UTC, martumoser requested changes

2022-11-03 14:55 UTC, DamianPalavecino commented on src/Components/Projects/index.jsx
> +  const [modalObject, setModalObject] = useState();
I don't have two modals. modalType is where I set what type of modal do I want to open (success, delete, employees) and modalObject is where I save a specific project object to delete it or show its employees by using the modal

2022-11-03 18:22 UTC, martumoser submitted a review, later dismissed

2022-11-03 19:45 UTC, PilarFernandezC approved these changes

2022-11-03 19:53 UTC, Juanoauil requested changes

2022-11-03 19:53 UTC, Juanoauil commented on src/Components/Projects/index.jsx
> +          {projects === undefined && <p>There are no projects</p>}
not well applied

2022-11-04 12:40 UTC, Juanoauil approved these changes

2022-11-04 13:56 UTC, Juanoauil approved these changes

2022-11-04 14:13 UTC, mara666 approved these changes
Good job Dami!

2022-11-05 16:20 UTC, merged