BaSP-TG-9-A: Admin - List and Delete
BaSP-a2022/marta-b-trackgenix-app pull request #5
Opened 2022-11-01 22:22 UTC by FabianDutraSilva

2022-11-02 01:57 UTC, martumoser requested changes

2022-11-02 01:57 UTC, martumoser commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);;
You have two semicolon at the end, please fix it

2022-11-02 01:58 UTC, martumoser requested changes
Please add a description to the PR. Thanks

2022-11-02 02:59 UTC, FabianDutraSilva commented on package.json
> +    "cors": "^2.8.5",
deleted!

2022-11-02 03:00 UTC, FabianDutraSilva commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);;
done!

2022-11-02 03:25 UTC, FabianDutraSilva commented on src/Components/Admins/modal-delete.module.css
> +    background-color: white;
corrected

2022-11-02 03:51 UTC, FabianDutraSilva commented on src/Components/Admins/modalDelete.jsx
> +const Modal = (props) => {
I read the article and i didn't understand how I should I destructure the props in this case. I understand I need to do the Modal const, because it's a Component that I'm going to use as a confirmation modal.

Is this a change request or is just an advice?
I'm going to ask mates to see if they understand too.

2022-11-02 14:53 UTC, mara666 commented on src/Components/Admins/modalDelete.jsx
> +const Modal = (props) => {
Fabi you can use something like this:
`const { openModal, showModal, closeModal } = props;`
So you can use each const where you need it, instead of `props`.
Another way is to directly pass the props names of the parent component.

2022-11-03 02:27 UTC, DamianPalavecino commented on src/Components/Admins/index.js
> +      <a href={`admins/form`}>
```suggestion
      <a href={'admins/form'}>
```
Remove backsticks (`) as you are not using a template literal in this line

2022-11-03 02:29 UTC, DamianPalavecino commented on src/Components/Admins/modal-delete.module.css
> +    background-color: rgba(0,0,0,0.5);
You have to choose between RGBA or HEX. You can't use both in the same file

2022-11-03 02:37 UTC, DamianPalavecino commented on src/Components/Admins/table.jsx
> +          <th id="actions">Actions</th>
```suggestion
          <th>Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Actions</th>
```
Those id properties are not used

2022-11-03 02:41 UTC, DamianPalavecino commented on src/Components/Admins/table.jsx
> +          <th id="actions">Actions</th>
Here you have 4 unused id properties (name, last-name, email, actions)

2022-11-03 02:45 UTC, DamianPalavecino commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);
Choose RGBA or HEX. You can't use both in the same file

2022-11-03 02:55 UTC, DamianPalavecino commented on src/Components/Admins/index.js
>  function Admins() {
```suggestion
const Admins = () => {
```
Use const instead

2022-11-03 15:27 UTC, FabianDutraSilva commented on src/Components/Admins/modalDelete.jsx
> +const Modal = (props) => {
`const Modal = ({ showModal, closeModal, admin, deleteAdmin }) => {`

done

2022-11-03 15:28 UTC, FabianDutraSilva commented on src/Components/Admins/index.js
> +      <a href={`admins/form`}>
`     <a href={'admins/form'}>
`
done

2022-11-03 15:29 UTC, FabianDutraSilva commented on src/Components/Admins/table.jsx
> +          <th id="actions">Actions</th>
erased, done

2022-11-03 15:32 UTC, FabianDutraSilva commented on src/Components/Admins/modal-delete.module.css
> +    background-color: rgba(0,0,0,0.5);
```
    background-color:#000000;
    opacity: 0.5;
```

2022-11-03 15:35 UTC, FabianDutraSilva commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);
done

2022-11-03 16:24 UTC, mara666 approved these changes
It's okey for me! Good job Fabi

2022-11-03 17:59 UTC, Juanoauil commented on package-lock.json
> +        "cors": "^2.8.5",
it is correct?

2022-11-03 18:23 UTC, martumoser approved these changes

2022-11-03 22:40 UTC, FabianDutraSilva commented on package-lock.json
> +        "cors": "^2.8.5",
Erased cors incorrectly imported into package.json

2022-11-04 14:48 UTC, EliasBermudez13 commented
Very good, but On Admins list Status column is missing.

2022-11-04 17:40 UTC, DamianPalavecino approved these changes
Changes were done correctly. Good job.

2022-11-05 04:24 UTC, FabianDutraSilva commented on src/Components/Admins/index.js
> +        <button className={styles.addButton}>Add admin</button>
Thank u Martu. Done with the team.

I paste the code here so it's easily accessible:

 <button
        onClick={() => {
          window.location.assign('admins/form');
        }}
        className={styles.addButton}
      >
        Add admin
      </button>

2022-11-05 18:35 UTC, Juanoauil commented on src/Components/Admins/table.jsx
> +        {admins === undefined || admins.length === 0 ? (
you can ask for (admins && admins.lenght > 0) ? ... : ...

2022-11-05 18:41 UTC, FabianDutraSilva commented on src/Components/Admins/table.jsx
> +        {admins === undefined || admins.length === 0 ? (
Fixed!
`     {!admins || admins.length <= 0 ? (`

2022-11-05 18:45 UTC, Juanoauil approved these changes

2022-11-05 19:29 UTC, cami-diaz approved these changes

2022-11-05 19:35 UTC, merged