BaSP-TG-9-B: Admin - Add and Edit
BaSP-a2022/marta-b-trackgenix-app pull request #7
Opened 2022-11-02 02:27 UTC by FabianDutraSilva

2022-11-03 03:34 UTC, Maxi-SR commented on src/Components/Admins/index.js
> +      <a href={`admins/form`}>
Try ` href=" admins/form" `

2022-11-03 03:35 UTC, Maxi-SR commented on src/Components/Admins/modal-delete.module.css
> +    background-color: rgba(0,0,0,0.5);
they recommend us to use colors in hexadecimal format

2022-11-03 03:37 UTC, Maxi-SR commented on src/Components/Admins/modalDelete.jsx
> +import styles from './modal-delete.module.css';
I think that is better use filenames in camel case

2022-11-03 03:41 UTC, Maxi-SR commented on src/Components/Admins/modalDelete.jsx
> +const Modal = (props) => {
Maybe you can use destructuring here

2022-11-03 03:54 UTC, Maxi-SR commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);;
Use hex color here

2022-11-03 04:30 UTC, DamianPalavecino commented on src/Components/Admins/form.jsx
> +    const adminId = params.get('id');
Here you can set the constants 'params' and 'taskId' as global variables so you don't have to repeat them at line 42

2022-11-03 16:23 UTC, FabianDutraSilva commented on src/Components/Admins/modalDelete.jsx
> +import styles from './modal-delete.module.css';
I think css file names should be in lower case. Ex: modal-delete

2022-11-04 00:39 UTC, FabianDutraSilva commented on src/Components/Admins/index.js
> +      <a href={`admins/form`}>
solved

2022-11-04 00:39 UTC, FabianDutraSilva commented on src/Components/Admins/modal-delete.module.css
> +    background-color: rgba(0,0,0,0.5);
we can keep it if it's due to opacity, so i'm leaving it like that

2022-11-04 04:06 UTC, FabianDutraSilva commented on src/Components/Admins/modalDelete.jsx
> +const Modal = (props) => {
done

2022-11-04 04:08 UTC, FabianDutraSilva commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);;
we are keeping rgba beacuse of opacity use

2022-11-04 04:08 UTC, FabianDutraSilva commented on src/Components/Admins/table.module.css
> +  background-color: rgba(55, 56, 103, 0.1);;
extra ;; fixed

2022-11-04 04:09 UTC, FabianDutraSilva commented on src/Components/Admins/form.jsx
> +    const adminId = params.get('id');
done

2022-11-04 19:36 UTC, martumoser requested changes

2022-11-04 19:36 UTC, martumoser commented on package.json
> +    "cors": "^2.8.5",
Not necessary to install cors on the frontend

2022-11-04 19:36 UTC, martumoser commented on src/Components/Admins/table.module.css
> +  }
Please fix indentation on this file

2022-11-05 04:28 UTC, FabianDutraSilva commented on package.json
> +    "cors": "^2.8.5",
Same mistake, sry. Fixed

2022-11-05 05:30 UTC, FabianDutraSilva commented on src/Components/Admins/table.module.css
> +  }
Done!

2022-11-05 19:59 UTC, DamianPalavecino commented on src/Components/Admins/form.jsx
> +    if (adminId !== null) {
```suggestion
    if (adminId) {
```

2022-11-05 20:01 UTC, DamianPalavecino commented on src/Components/Admins/form.jsx
> +          alert('Admin updated successfully');
```suggestion
          alert(message);
```
Here you can use the message from the backend

2022-11-05 20:02 UTC, DamianPalavecino commented on src/Components/Admins/form.jsx
> +          alert('Admin created successfully');
same as above

2022-11-05 20:07 UTC, FabianDutraSilva commented on src/Components/Admins/form.jsx
> +    if (adminId !== null) {
done

2022-11-05 20:07 UTC, FabianDutraSilva commented on src/Components/Admins/form.jsx
> +          alert('Admin created successfully');
done

2022-11-05 20:07 UTC, DamianPalavecino approved these changes
Approved, good job

2022-11-05 20:08 UTC, FabianDutraSilva commented on src/Components/Admins/form.jsx
> +          alert('Admin updated successfully');
excelent correction. Done

2022-11-05 20:22 UTC, Juanoauil approved these changes

2022-11-05 23:53 UTC, EliasBermudez13 commented
When editing it should show the status that the admin already had (active or inactive), but it's always showing inactive.

2022-11-06 19:45 UTC, EliasBermudez13 commented
> Al editar, debería mostrar el estado que ya tenía el administrador (activo o inactivo), pero siempre muestra inactivo.
This issue was explained in another ticket to be fixed later after merging. So everything in order, it's approved

2022-11-06 20:18 UTC, martumoser approved these changes

2022-11-06 21:14 UTC, merged